name: Test Link 4K Video Downloader

on:
  schedule:
    - cron: "0 12 * * *"

  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Testing link 4K Video Downloader
        run: |
          link="https://www.4kdownload.com/downloads"
          
          for i in {1..35}; { printf '─' >> $GITHUB_STEP_SUMMARY; }; printf "\n" >> $GITHUB_STEP_SUMMARY
          printf "Search latest version: "

          version="$(grep -Eom1 "([0-9]+[.]){2}[0-9]+" <(grep -A5 "    4K Video Downloader+" <(links -dump "$link")))"

          printf "\033[1;32m$version\033[m\n" >> $GITHUB_STEP_SUMMARY
          for i in {1..35}; { printf '─' >> $GITHUB_STEP_SUMMARY; }; printf "\n" >> $GITHUB_STEP_SUMMARY
          
