name: Test Link 4K Video Downloader

on:
  schedule:
    - cron: "0 12 * * *"

  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt install links

      - name: Test Link 4kdownload
        run: |
          export link="https://www.4kdownload.com/downloads"
          status="$(curl -i $link)"
          echo StatusCode for link $link: $status >> $GITHUB_STEP_SUMMARY

      - name: Testing link 4K Video Downloader
        run: |
          version="$(grep -Eom1 "([0-9]+[.]){2}[0-9]+" <(grep -A5 "    4K Video Downloader+" <(links -dump "$link")))"
          printf "Search latest version: $version\n" >> $GITHUB_STEP_SUMMARY
